services:
  - type: web
    name: minio
    env: docker
    plan: starter
    disk:
      name: minio-data
      mountPath: /data
      sizeGB: 10
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MINIO_ROOT_USER
        value: minioadmin
      - key: MINIO_ROOT_PASSWORD
        value: minioadmin123
